name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

  build-and-scan:
    needs: lint
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: myapp:${{ github.sha }}
          
      # Download Trivy vulnerability DB
      - name: Download Trivy DB
        run: |
          mkdir -p $HOME/.cache/trivy
          wget -q -O - https://github.com/aquasecurity/trivy-db/releases/latest/download/trivy-db.tar.gz | tar -xzf - -C $HOME/.cache/trivy

      # Install Trivy directly instead of using the action
      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy
          
      - name: Scan image with Trivy
        run: |
          trivy image \
            --cache-dir $HOME/.cache/trivy \
            --no-progress \
            --exit-code 1 \
            --severity HIGH,CRITICAL \
            myapp:${{ github.sha }}

            
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    needs: build-and-scan
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: your-registry/myapp:dev-${{ github.sha }}

      # Add later

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: build-and-scan
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            your-registry/myapp:latest
            your-registry/myapp:${{ github.sha }}

      # Add later
